name: remote ssh command
on:
  push:
    branches:
      - Stable
  workflow_dispatch:
    branches:
      - Stable
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using key
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ${{ secrets.WORK_DIR }}
          pwd
          git pull
          cd ..
          docker-compose restart